-- Replace with "<studentid>"_products, i.e. ds21m19_products
CREATE TABLE moh_products
(
  code varchar,  
  name varchar,
  description varchar,
  sku int4,
  price numeric,
  category varchar,
  model_number varchar
);

-- Replace with  "<studentid>"_products, i.e. ds22m19_products
INSERT INTO moh_products
VALUES
('AVOCA', 'Avocado', 'Add Avocado', 176, 1, 'Add-ons', 'ADD AVOCADO'),
 ('CHEES', 'Cheese', 'Add Cheese', 177, 1, 'Add-ons', 'ADD DELI CHEESE'),
 ('VEG', 'Veggies', 'Add Veggies', 178, 1, 'Add-ons', 'ADD VEGGIES'),
 ('JALA', 'Jalapeno', 'Jalapeno', 1, 0.92, 'Bagels', 'BAGEL'),
 ('MULTI', 'Multiseed', 'Multiseed', 2, 0.92, 'Bagels', 'BAGEL'),
 ('ONION', 'Onion', 'Onion', 3, 0.92, 'Bagels', 'BAGEL'),
 ('PLAIN', 'Plain', 'Plain', 4, 0.92, 'Bagels', 'BAGEL'),
 ('POPPY', 'Poppy Seed', 'Poppy Seed', 5, 0.92, 'Bagels', 'BAGEL'),
 ('RYE', 'Rye Pumpernickle', 'Rye Pumpernickle', 6, 0.92, 'Bagels', 'BAGEL'),
 ('SALT', 'Salt', 'Salt', 7, 0.92, 'Bagels', 'BAGEL'),
 ('SESAM', 'Sesame', 'Sesame', 8, 0.92, 'Bagels', 'BAGEL'),
 ('WHEAT', 'Whole Wheat', 'Whole Wheat', 9, 0.92, 'Bagels', 'BAGEL'),
 ('TOMAT', 'Sundried Tomato', 'Sundried Tomato', 10, 0.92, 'Bagels', 'BAGEL'),
 ('GARLC', 'Garlic', 'Garlic', 11, 0.92, 'Bagels', 'BAGEL'),
 ('EGG', 'Egg', 'Egg', 12, 0.92, 'Bagels', 'BAGEL'),
 ('CHOC', 'Chocolate Chip', 'Chocolate Chip', 13, 0.92, 'Bagels', 'BAGEL'),
 ('COMBO', 'Combo', 'Combo', 14, 0.92, 'Bagels', 'BAGEL'),
 ('CINNA', 'Cinnamon Raisin', 'Cinnamon Raisin', 15, 0.92, 'Bagels', 'BAGEL'),
 ('BLUE', 'Blueberry', 'Blueberry', 16, 0.92, 'Bagels', 'BAGEL'),
 ('WHT-S', 'Whole Wheat Sesame', 'Whole Wheat Sesame', 18, 0.92, 'Bagels', 'BAGEL'),
 ('1/2DZ', '1/2 Dozen Bagels', '1/2 Dozen Bagels', 20, 6.75, 'Bagels', '1/2 DZ BGELS'),
 ('DZN', 'Baker''s Dozen Bagels', 'Baker''s Dozen Bagels', 26, 11.95, 'Bagels', 'ONE DOZEN BAGEL'),
 ('BG+GM', 'Bagel/gourmet cream cheese', 'Bagel + gourmet cream cheese', 28, 3.25, 'Bagels', 'GOUR CRM CH TOFU'),
 ('BG+LX', 'Bagel/lox cr ch', 'Bagel + lox cream cheese', 29, 3.75, 'Bagels', 'GOURMET LOX SPREAD'),
 ('BG+CR', 'Bagel/cr ch', 'Bagel + cream cheese', 30, 2.65, 'Bagels', 'CLASSIC CRM CH'),
 ('DEVIL', 'Devil Eggs', 'Devil Eggs', 165, 3.25, 'Breakfast', 'DEVIL EGG'),
 ('FRITT', 'Roasted Red Pepper Frittata Slic', 'Roasted Red Pepper Frittata Slic', 166, 5.95, 'Breakfast', null),
 ('BURRT', 'Breakfast Burrito with egg & pot', 'Breakfast Burrito with egg & pot', 167, 5.95, 'Breakfast', 'BURRITO'),
 ('YOGUR', '16 oz. Parfait Yogurt with fresh', '16 oz. Parfait Yogurt with fresh', 168, 5.95, 'Breakfast', 'YOGOURT'),
 ('POP', 'Poppy Seed Challah 1.25 Lb.', 'Poppy Seed Challah 1.25 Lb.', 157, 5.25, 'Challah', 'REG CHALLA'),
 ('6RLLS', 'Bag of 6 pcs. of Plain Challah R', 'Bag of 6 pcs. of Plain Challah R', 159, 4, 'Challah', '6 C ROLLS'),
 ('1/8CK', '1/8 Cheese Cake', '1/8 Cheese Cake', 137, 19.95, 'Cheesecake', 'CH CAKE'),
 ('1/4CK', '1/4 Sheet Cheese Cake', '1/4 Sheet Cheese Cake', 138, 58.95, 'Cheesecake', 'CH CAKE'),
 ('1/2CK', '1/2 Sheet Cheese Cake', '1/2 Sheet Cheese Cake', 139, 98.95, 'Cheesecake', 'CH CAKE'),
 ('CAPP', 'Cappuccino', 'Cappuccino', 1185, 2.5, 'Coffee', '12OZ CAPPUCINO'),
 ('COFEE', 'Coffee', 'Coffee', 1186, 1.5, 'Coffee', '12OZ COFFEE'),
 ('LATTE', 'Latte', 'Latte', 1188, 2.5, 'Coffee', '12OZ LATTE'),
 ('MOCHA', 'Mocha', 'Mocha', 1189, 3, 'Coffee', '12OZ MOCHA'),
 ('XPRSO', 'Espresso', 'Espresso', 196, 0.6, 'Coffee', 'XTRA SHOT'),
 ('OATM', 'Oatmeal Raisin [Dairy]', 'Oatmeal Raisin [Dairy]', 87, 1.45, 'Cookies', 'COOKIE'),
 ('M&M', 'M & M [Dairy]', 'M & M [Dairy]', 88, 1.25, 'Cookies', 'COOKIE'),
 ('SUGAR', 'Sugar Cookie [Dairy]', 'Sugar Cookie [Dairy]', 89, 1.45, 'Cookies', 'COOKIE'),
 ('FCHOC', 'Filled Chocolate Cokie [Dairy]', 'Filled Chocolate Cokie [Dairy]', 90, 1.45, 'Cookies', 'COOKIE'),
 ('PNUT', 'Peanut Butter [Dairy]', 'Peanut Butter [Dairy]', 91, 1.45, 'Cookies', 'COOKIE'),
 ('MACAR', 'Filled Macaroon Cookie [Dairy]', 'Filled Macaroon Cookie [Dairy]', 92, 1.45, 'Cookies', 'COOKIE'),
 ('FPNUT', 'Filled Peanut Butter Cookie [Dai', 'Filled Peanut Butter Cookie [Dai', 93, 1.45, 'Cookies', 'COOKIE'),
 ('SPRNK', 'Sprinkle Cookie [Parve]', 'Sprinkle Cookie [Parve]', 99, 1.25, 'Cookies', 'COOKIE'),
 ('B&W', 'Black & White Cookie [Parve]', 'Black & White Cookie [Parve]', 100, 2.25, 'Cookies', 'B & W'),
 ('RASPB', 'Raspberry Hamentashen $11.95/Lb ', 'Raspberry Hamentashen $11.95/Lb ', 101, 11.95, 'Hamentashen', 'HAMENTASHEN'),
 ('PRUNE', 'Prune Hamentashen $11.95/Lb. Par', 'Prune Hamentashen $11.95/Lb. Par', 102, 11.95, 'Hamentashen', 'HAMENTASHEN'),
 ('APRCT', 'Apricot Hamentashen $11.95/Lb Pa', 'Apricot Hamentashen $11.95/Lb Pa', 104, 11.95, 'Hamentashen', 'HAMENTASHEN'),
 ('MART', 'Martinelli''s juice', 'Martinelli''s juice', 179, 1.5, 'Drinks', 'MARTINELLI ,S JUICE'),
 ('MART2', 'Martinelli''s juice - sparkling', 'Martinelli''s juice - sparkling', 180, 1.5, 'Drinks', 'MARTINELLI'' SPARK'),
 ('ODWLA', 'Odwalla', 'Odwalla', 181, 4, 'Drinks', 'ODWALLA 160Z'),
 ('DRBRN', 'Dr. Brown', 'Dr. Brown', 182, 1.5, 'Drinks', 'DR BROWN'),
 ('TEA', 'Tea', 'Tea', 183, 1.35, 'Drinks', 'TEA'),
 ('SNPPL', 'Snapple', 'Snapple', 184, 1.5, 'Drinks', 'SNAPPLE'),
 ('SODA', 'Soda', 'Soda', 197, 1.5, 'Drinks', 'CAN SODA'),
 ('ORNGA', 'Orangina', 'Orangina', 198, 1.5, 'Drinks', 'ORANGINA'),
 ('WATER', 'Bottled water', 'Bottled water', 199, 1.5, 'Drinks', 'WATER'),
 ('URN', 'TULLY''S COFFEE TO GO', 'TULLY''S COFFEE TO GO', 201, 17, 'Coffee', 'COFFEE URN'),
 ('VEGGI', 'Vegetarian Frittata [PARVE]', 'Vegetarian Frittata [PARVE]', 174, 24.95, 'Frittata Trays', 'V FRITTA T'),
 ('SPNCH', 'Spinach', 'Spinach', 146, 3.95, 'Knishes', 'KNISH'),
 ('BROCC', 'Broccoli', 'Broccoli', 148, 3.95, 'Knishes', 'KNISH'),
 ('KASHA', 'Kasha', 'Kasha', 149, 3.95, 'Knishes', 'KNISH'),
 ('8OZ', '_ Lb. Gourmet Wild Lox [8oz.]', '_ Lb. Gourmet Wild Lox [8oz.]', 83, 15, 'Lox', '1/2# LX GRMT'),
 ('4OZ', 'Gourmet Wild Lox [4oz.]', 'Gourmet Wild Lox [4oz.]', 84, 7.5, 'Lox', '1/4#LX GRMT'),
 ('BNANA', 'Banana Nut', 'Banana Nut', 151, 3.25, 'Muffins', 'MUFFINS'),
 ('CARRT', 'Glorious Morning - Carrot', 'Glorious Morning - Carrot', 152, 3.25, 'Muffins', 'MUFFINS'),
 ('LEMON', 'Lemon Poppy Seed', 'Lemon Poppy Seed', 154, 3.25, 'Muffins', 'MUFFINS'),
 ('BUTTR', '4.5 oz. Butter Croissants', '4.5 oz. Butter Croissants', 111, 2.95, 'Croissants', 'CROISS SDW'),
 ('CREAM', '4.25 oz. Cream Cheese Croissants', '4.25 oz. Cream Cheese Croissants', 113, 2.95, 'Croissants', 'CROISS SDW'),
 ('STRAW', '4.25 oz. Strawberry Cream Cheese', '4.25 oz. Strawberry Cream Cheese', 114, 2.95, 'Croissants', 'CROISS SDW'),
 ('APPLE', '4.55 oz. Apple Turnovers', '4.55 oz. Apple Turnovers', 116, 2.95, 'Turnovers', 'PASTRIES'),
 ('CHRRY', '4.55 oz. Cherry Turnovers', '4.55 oz. Cherry Turnovers', 117, 2.95, 'Turnovers', 'PASTRIES'),
 ('SAMON', 'Smoked Baked Salmon Salad', 'Smoked Baked Salmon Salad', 50, 6.95, 'Salads', '8OZ FISH SALADS'),
 ('WHITE', 'Smoked White Fish Salad', 'Smoked White Fish Salad', 51, 6.95, 'Salads', '8OZ FISH SALADS'),
 ('HRCRM', 'Herring in Cream Sauce', 'Herring in Cream Sauce', 52, 6.5, 'Salads', '8OZ FISH SALADS'),
 ('HRWIN', 'Herring in Wine Sauce', 'Herring in Wine Sauce', 53, 6.5, 'Salads', '8OZ FISH SALADS'),
 ('TUNA', 'Izzy''s Tuna Salad', 'Izzy''s Tuna Salad', 54, 5.25, 'Salads', '8OZ EGGPLT TUNA SA'),
 ('HUMUS', 'Hummus or Veggie "Chopped Liver"', 'Hummus or Veggie "Chopped Liver"', 63, 4.5, 'Salads', '8OZ HUMMUS/VCL'),
 ('LENTL', 'Lentil with carrots 12oz.', 'Lentil with carrots 12oz.', 79, 4.55, 'Soups', '120Z SOUP'),
 ('MINES', 'Minestrone 12oz.', 'Minestrone 12oz.', 80, 4.55, 'Soups', '120Z SOUP'),
 ('BARLY', 'Barley 12oz.', 'Barley 12oz.', 81, 4.55, 'Soups', '120Z SOUP'),
 ('FLAT', 'Flatgels', 'Flatgels', 21, 1.95, 'Specialty Bagels', 'FLAT BAGEL'),
 ('CHLLA', 'Challa Bagel', 'Challa Bagel', 24, 4.95, 'Specialty Bagels', 'CHELLA BGL'),
 ('ORNG', 'Belgian Orange Chocolate Cream C', 'Belgian Orange Chocolate Cream C', 34, 3.95, 'Spreads', '8OZ GOUR CRM CH'),
 ('WLNUT', 'Walnut Raisin Cream Cheese', 'Walnut Raisin Cream Cheese', 35, 3.95, 'Spreads', '8OZ GOUR CRM CH'),
 ('CLSSC', 'Classic Cream Cheese', 'Classic Cream Cheese', 36, 3.5, 'Spreads', '8OZ CLASSIC'),
 ('LOFAT', 'Low - Fat Cream Cheese', 'Low - Fat Cream Cheese', 37, 3.5, 'Spreads', '8OZ GOUR CRM CH'),
 ('CCMBR', 'Cucumber Scallion Cream Cheese', 'Cucumber Scallion Cream Cheese', 38, 3.95, 'Spreads', '8OZ GOUR CRM CH'),
 ('CHIVE', 'Chive Cream Cheese', 'Chive Cream Cheese', 39, 3.95, 'Spreads', '8OZ GOUR CRM CH'),
 ('TOMTO', 'Sundried Tomato Cream Cheese', 'Sundried Tomato Cream Cheese', 41, 3.95, 'Spreads', '8OZ GOUR CRM CH'),
 ('LOX', 'Lox Spread', 'Lox Spread', 42, 4.5, 'Spreads', '8OZ LOX SPREAD'),
 ('BOLV', 'Black Olive Cream Cheese', 'Black Olive Cream Cheese', 43, 3.95, 'Spreads', '8OZ GOUR CRM CH'),
 ('GOLV', 'Green Olive & Garlic Cream Chees', 'Green Olive & Garlic Cream Chees', 44, 3.95, 'Spreads', '8OZ GOUR CRM CH'),
 ('GOLV2', 'Green Olive & Pimento Cream Chee', 'Green Olive & Pimento Cream Chee', 45, 3.95, 'Spreads', '8OZ GOUR CRM CH'),
 ('REDPP', 'Roasted Red Pepper Cream Cheese', 'Roasted Red Pepper Cream Cheese', 46, 3.95, 'Spreads', '8OZ GOUR CRM CH'),
 ('SALSA', 'Mexican Salsa Cream Cheese', 'Mexican Salsa Cream Cheese', 47, 3.95, 'Spreads', '8OZ GOUR CRM CH'),
 ('JLPNO', 'Jalapeno Cream Cheese', 'Jalapeno Cream Cheese', 49, 3.95, 'Spreads', '8OZ GOUR CRM CH'),
 ('EGGPL', 'Grilled Eggplant with Mushrooms ', 'Grilled Eggplant with Mushrooms ', 74, 6.95, 'Wraps', 'WRAPS EA'),
 ('BFAST', 'Egglette', 'Egglette', 169, 3.5, 'Breakfast', 'EGGLETTE');
